### ISSUE TITLE
Gemfile requires Roda 3.13, but it is not released

### ISSUE THREAD

**Issue by fdr** [jeremyevans/roda-sequel-stack#10]
Just thought to let you know. I downgraded the required version to 3.12.

**Comment by jeremyevans** [comment]
The stack master branch uses a new plugin in Roda's master branch that will be shipping in roda 3.13, which will be released in a few days.  So this is currently expected, but I agree it's probably not a good practice.  In the future I'll wait until after the release of the related gems before updating roda-sequel-stack.  I'll keep this open in the meantime just in case other people run into this issue.

**Comment by jeremyevans** [comment]
I just released Roda 3.13.0, so this issue has been fixed.  In the future I won't push changes to roda-sequel-stack until the components in the stack have been released.
