### ISSUE TITLE
`zsh` does not work with `rake setup[MyApp]`

### ISSUE THREAD

**Issue by ababich** [jeremyevans/roda-sequel-stack#11]
```
> rake setup[MyApp]
zsh: no matches found: setup[MyApp]
```

I suggest to change this to `rake "setup[MyApp]"`

or [at least] make some side note for `zsh` case

**Comment by jeremyevans** [comment]
Quoting the argument sounds fine to me, so it would be `rake "setup[MyApp]"`.  Do you want to send in a pull request for that?

**Comment by ababich** [comment]
https://github.com/jeremyevans/roda-sequel-stack/pull/12

**Comment by jeremyevans** [comment]
Merged #12
