### ISSUE TITLE
can't modify frozen #<Class:Object> (FrozenError)

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [jeremyevans/roda-sequel-stack#14]
Thanks for the great work!
But when I try to test this project I have problem.

After `rake dev_up` I try to start `rackup config.ru` and have error:
```.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:112:in `<top (required)>': can't modify frozen #<Class:Object> (FrozenError)```

This problem related to `refrigerator` into `config.ru`.
When refrigerator block was removed, all works fine.

**Comment by jeremyevans** [comment]
Thanks for the report.  Looks like my attempted fix for this in #13 was incorrect.  I'll push up a new fix shortly.
