### ISSUE TITLE
Unreloader in the models.rb

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [jeremyevans/roda-sequel-stack#15]
As I understand, inside `config.ru` you use `unreloader` only for developer mode. But in the `models.rb` (12-17 rows) you add it for all modes. Can you explain the main point for this case?
On my opinion, we don't need to use it for non developer mode. Is not it?

**Comment by jeremyevans** [comment]
`config.ru` actually always uses rack-unreloader, but it only sets up the reloading in development mode (`reload: dev`). In `models.rb`, if the `Unloader` isn't already defined, one is defined but it is set to not actually do any reloading (`reload: false`).  This is done so the same API can be used if the `models.rb` file is required directly (i.e. when not running the app using `config.ru`).

Hopefully that explains things, but if not, please let me know.

**Comment by Serhiy-Nazarov** [comment]
understood. thanks!
