### ISSUE TITLE
the `logger` is initialized only in development mode

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [jeremyevans/roda-sequel-stack#16]
```ruby
Unreloader = Rack::Unreloader.new(subclasses: %w'Roda Sequel::Model', logger: logger, reload: dev){App}
```
In the non development mode `logger` doesn't exist. Isn't it?

**Comment by jeremyevans** [comment]
Correct, but the `:logger` option accepts `nil` as a valid value for no logger, so this is not a problem.

**Comment by Serhiy-Nazarov** [comment]
@jeremyevans 
I mean `logger` variable is missing. So it's not nil.
If the environment is not `development`, `logger` variable is not defined. And it will exception.

**Comment by jeremyevans** [comment]
Above this code, we have:

```ruby
if dev
  require 'logger'
  logger = Logger.new($stdout)
end
```

In Ruby, if `dev` is false, then `logger` is `nil`.  

If you are actually getting an exception raised, please post the backtrace.

**Comment by Serhiy-Nazarov** [comment]
Thanks @jeremyevans 
This is new knowledge for me :)
