### ISSUE TITLE
PreparedStatementsSafe

### ISSUE THREAD

**Issue by PetrKaleta** [jeremyevans/roda-sequel-stack#17]
Is there a reason why you're not using `PreparedStatementsSafe` plugin?

**Comment by jeremyevans** [comment]
Not really.  These days it might be better to not load the `prepared_statements` plugin at all.  If you want to send a pull request for either removing the plugin or switching it to the safe version, I can merge it.

**Comment by PetrKaleta** [comment]
Aha okay, can you please be more specific why it’s not a good idea these days?

Thank you

**Comment by jeremyevans** [comment]
It doesn't help performance that much in most cases, and it adds complexity.  It only helps security if you expect there to be a bug in how values are literalized to SQL, in which case there are probably much larger issues.  It prevents the use of values that can be literalized to SQL but can not be used as prepared statement values.
