### ISSUE TITLE
roda for API

### ISSUE THREAD

**Issue by eduscrakozabrus** [jeremyevans/roda-sequel-stack#19]
It would be great to have a ready-made assembly for the API (jsonapi), with authorization, multy-tenant mode (by schemas or databases)

**Comment by eduscrakozabrus** [comment]
may by multi-tenant as gem apartment for migrate..

**Comment by jeremyevans** [comment]
That goes beyond the purpose of this project.  I'm not disagreeing that it would be great to have a project that does that, but it isn't this project.  Please consider forking this project and adding those features to the fork if you would like to see such a project.
