### ISSUE TITLE
`ENV SESSION SECRET` not being assigned proper value

### ISSUE THREAD

**Issue by goseinthemachine** [jeremyevans/roda-sequel-stack#20]
I was testing the assignment of the ENV variables by printing to the console for the rake setup task and noticed that the `ENV['#{upper_name}_SESSION_SECRET'] ` is being assigned the value `"postgres:///#{lower_name}_test?user=#{lower_name}"` because the code for the session key is not surrounded by double quotes. Without the quotes surrounding `#{...}` it is just a comment and is ignored. 

Lines 127, 130, and 133 should be this `ENV['#{upper_name}_SESSION_SECRET'] ||= "#{random_bytes.call}".unpack('m')[0]`, right?

https://github.com/jeremyevans/roda-sequel-stack/blob/3bdcda8536646da226e27e0efc4702f87d519f67/Rakefile#L125-L136

**Comment by jeremyevans** [comment]
The example you are showing is inside a heredoc:

https://github.com/jeremyevans/roda-sequel-stack/blob/3bdcda8536646da226e27e0efc4702f87d519f67/Rakefile#L124-L137

So the interpolation using `#{}` will work even though inside the heredoc, it appears inside a single quoted string.  If you run the `setup` task normally, you should see the correct result in the produced `.env.rb`.  Example:

```
$ git clone ../roda-sequel-stack/
$ cd roda-sequel-stack/
$ rake setup[Foo]
$ cat .env.rb
case ENV['RACK_ENV'] ||= 'development'
when 'test'
  ENV['FOO_SESSION_SECRET'] ||= "ChyZBn37UwdvIsxGQR6vi0tH0/QoWWw1kopy2LhY8/z4lk4mDAjBnZjCjxkY\n1A7KlRTUX4PzLeWHYUySOQzP7g==\n".unpack('m')[0]
  ENV['FOO_DATABASE_URL'] ||= "postgres:///foo_test?user=foo"
when 'production'
  ENV['FOO_SESSION_SECRET'] ||= "79gktb8B9Z4wcaBlD6pWgu7X/FG3aLkujfP7VX+KvP36fKmdNiaP8B5KwKUv\nQXsPMRiePqxQZL9qWTjETrbPVQ==\n".unpack('m')[0]
  ENV['FOO_DATABASE_URL'] ||= "postgres:///foo_production?user=foo"
else
  ENV['FOO_SESSION_SECRET'] ||= "xik5FUwOE0rETiFSGkoZ3ZQ2ibqNEpnRwhjeeiE9yBFXRnWzsgFL1sfpPbRN\nifzDiZBVCp7bTWXJaX6wZKDJxQ==\n".unpack('m')[0]
  ENV['FOO_DATABASE_URL'] ||= "postgres:///foo_development?user=foo"
end
```

**Comment by goseinthemachine** [comment]
You are right. I was piecing the Rakefile together and didn't notice the heredoc. Thank you for clarifying this I appreciate it.
