### ISSUE TITLE
Can't find executable rake

### ISSUE THREAD

**Issue by webhive** [jeremyevans/roda-sequel-stack#23]
On a fresh install got the following error

$ rake "setup[MyApp]"
bundler: failed to load command: rake (<my home dir>/.asdf/installs/ruby/2.7.1/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?

Fixed by adding rake to Gemfile

**Comment by jeremyevans** [comment]
I'm not sure why you are getting a bundler error here, since roda-sequel-stack itself never loads bundler.  Do you have some environment that automatically loads bundler when running rake?

**Comment by webhive** [comment]
> I'm not sure why you are getting a bundler error here, since roda-sequel-stack itself never loads bundler. Do you have some environment that automatically loads bundler when running rake?

Hmm seems yes, so probably my issue

```
$ which rake
rake: aliased to bundle exec rake
```
