### ISSUE TITLE
Move DB object freeze call after the app declaration

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/roda-sequel-stack#24]
The [models.rb file calls DB.freeze at the bottom](https://github.com/jeremyevans/roda-sequel-stack/blob/f3d555f978c4bc56e38ddfea643faabaeccea2d7/models.rb#L28). 

As it was noted in [this rodauth-oauth issue](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/merge_requests/85), this conflicts directly to how other "same stack" (if you consider rodauth "same stack") may still interact and extend the DB object at configuration time.

Although this was reported as a `rodauth-oauth` issue, it just follows the convention [set by rodauth itself](https://github.com/jeremyevans/rodauth/blob/bb760a6d0be1d582491fa5bc5ac976c275f77717/lib/rodauth/features/base.rb#L402), so it could also happen there.

The solution would be to move the call to [after the roda app initializes](https://github.com/jeremyevans/roda-sequel-stack/blob/f3d555f978c4bc56e38ddfea643faabaeccea2d7/app.rb#L89).

**Comment by jeremyevans** [comment]
My preferred solution is to load the Database extension in db.rb.  That should fix the issue.  I don't think there is an example of using an extension there, so I should probably add one.

**Comment by HoneyryderChuck** [comment]
Isn't that going to result in the same issue? If I use rodauth and load the plugin in the roda app, and the extension loads in the post_configure callback, it'll blow up, because the database object has already been frozen.

**Comment by jeremyevans** [comment]
If users load the extension before the Database is frozen, then attempting to load it again after it is frozen won't blow up.

**Comment by HoneyryderChuck** [comment]
If users take this project as their template, "If users load the extension before the Database is frozen" won't happen, as `app.rb` loads the `models.rb` at the top, then loads the roda app. If I'm to add `rodauth` here, I'll probably load it in the roda app defined there. Therefore, a new user will see this error and scratch his head while trying to fix it.

In order to remove friction for new users, I'd propose to delay freezing of the DB until after the Roda app is created. Overall it should (arguably) be best practice to freeze objects until "bootstrap" (which is what the roda app does, given it freezes in `rackup.ru`).

**Comment by jeremyevans** [comment]
If we take that approach, for consistency, in addition to `DB.freeze`, we need to move `Sequel::Model.freeze_descendents`.  Then we need to update the specs so that both are called in every spec suite after loading the code but before running the specs.  It would result in `irb -r ./models` loading a non-frozen database and models, though I suppose some would consider that a benefit.

 I agree with your point that it would remove friction for new users.  It does result in unnecessary duplication, which is why I've been against it.  But I suppose as long as both test and production are still using frozen database/models, that's what's important.

**Comment by HoneyryderChuck** [comment]
Didn't take the tests into consideration, but I agree with the argument. The duplication point stands, and this is a choice motivated by rodauth, which isn't part of the template. Perhaps freezing `DB` as part of freezing the `App` could work? Smth like:

```ruby
class App < Roda
  def freeze
    DB.freeze
    super
  end
end
```

As a final suggestion. Other than that, thx for doing the change!

**Comment by jeremyevans** [comment]
That seems like a good idea, and would reduce duplication somewhat.

**Comment by greenfork** [comment]
Can confirm that it works, thanks!
